---
- hosts: npf_gameservers
  gather_facts: false
  tasks:
  - name: apt tools install
    apt:
      name: software-properties-common
      state: present

  - name: Downloader hpPublicKey1024.pub
    get_url:
      url: http://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub
      dest: /tmp/hpPublicKey1024.pub
      mode: 0440
    become: true

  - name: Downloader hpPublicKey2048.pub
    get_url:
      url: http://downloads.linux.hpe.com/SDR/hpPublicKey2048.pub
      dest: /tmp/hpPublicKey2048.pub
      mode: 0440
    become: true

  - name: Downloader hpPublicKey2048_key1.pub
    get_url:
      url: http://downloads.linux.hpe.com/SDR/hpPublicKey2048_key1.pub
      dest: /tmp/hpPublicKey2048_key1.pub
      mode: 0440
    become: true

  - name: Downloader hpePublicKey2048_key1.pub
    get_url:
      url: http://downloads.linux.hpe.com/SDR/hpePublicKey2048_key1.pub
      dest: /tmp/hpePublicKey2048_key1.pub
      mode: 0440
    become: true  

  - name: Install hpPublicKey1024.pub
    command: apt-key add /tmp/hpPublicKey1024.pub
    become: true  

  - name: Install hpPublicKey2048.pub
    command: apt-key add /tmp/hpPublicKey2048.pub
    become: true  

  - name: Install hpPublicKey2048_key1.pub
    command: apt-key add /tmp/hpPublicKey2048_key1.pub
    become: true  

  - name: Install hpePublicKey2048_key1
    command: apt-key add /tmp/hpePublicKey2048_key1.pub
    become: true

  - name: add apt source
    copy: content="deb http://downloads.linux.hpe.com/SDR/repo/mcp xenial/10.40 non-free" dest=/etc/apt/sources.list.d/hpe.list

  - name: update apt
    apt:
      name: hp-health
      state: present
      update_cache: yes
