---
- hosts: npf_gameservers
  
  tasks:
#    - name: restart btsync
#      service: name=btsync state=restarted
#
#    - name: Install GPG key for btsync
#      apt_key:
#        id=6BF18B15
#        state=present
#        url=http://stinkfoot.org:11371/pks/lookup?op=get&search=0x40FC0CD26BF18B15
#
#    - name: Add the deb repo for btsync
#      apt_repository:
#        repo='deb http://debian.yeasoft.net/btsync wheezy main'
#        state=present
#
#    - name: Install btsync
#      apt: pkg=btsync state=installed

     - name: ensure git is installed
       apt: pkg=git state=installed

     - name: git clone bbcp
       git: clone=yes repo=http://www.slac.stanford.edu/~abh/bbcp/bbcp.git dest=/root/bbcp
