---
- hosts: npf_gameservers-current-rack
  tasks:
  - name: Install screen
    apt:
      name: "screen"
  - name: Accept SteamCMD License
    debconf:
      name: "steamcmd"
      question: "steam/question"
      value: "I AGREE"
      vtype: "select"
  - name: Install SteamCMD
    apt:
      name: "steamcmd"
  - name: Updateing SteamCMD
    command: /usr/games/steamcmd +exit
    become: true
    become_user: steam
