---
#- hosts: npf_gameservers-current-rack
- hosts: npf_gameservers
  tasks:

  - name: "FIX: Ubuntu 16.04 LTS dosen't come with certain modules, required by ansible"
    become: yes
    become_user: root
    become_method: sudo
    raw: apt-get install python-minimal aptitude -y

  - name: "Accept SteamCMD license"
    become: yes
    become_user: root
    become_method: sudo
    debconf:
      name: "steamcmd"
      question: "steam/question"
      value: "I AGREE"
      vtype: "select"

  - name: "Update, Upgrade, Remove and Clean APT Packages"
    become: yes
    become_user: root
    become_method: sudo
    apt:
      update_cache: yes
      upgrade: full
      cache_valid_time: 86400 #one day
      state: latest

  - name: "Install screen APT Package"
    become: yes
    become_user: root
    become_method: sudo
    apt:
      name: screen
      state: latest

  - name: "Install SteamCMD APT Package"
    become: yes
    become_user: root
    become_method: sudo
    apt:
      name: steamcmd
      state: latest

  - name: Creating directory for repository
    file: path=/srv/csgo state=directory

  - name: Creating directory for logs
    file: path=/srv/logs state=directory

  - name: Syncing /srv directory
    synchronize:
     src: /srv/
     dest: /srv
     delete: yes
     recursive: yes

  - name: Updateing directory owner on /srv
    file:
     path: /srv
     owner: steam
     group: steam
     recurse: yes

  - name: Updateing SteamCMD
    command: /usr/games/steamcmd +exit
    become: true
    become_user: steam
