---
- hosts: npf_gameservers-current-rack
  tasks:

  - name: Syncing /srv/csgo directory
    synchronize:
     src: /srv/csgo/
     dest: /srv/csgo

  - name: Updateing directory owner on /srv
    file:
     path: /srv
     owner: steam
     group: steam
     recurse: yes
