---
- hosts: npf_gameservers
  gather_facts: no
  tasks:
  - name: Updateing /srv/server.sh script
    synchronize:
     src: /srv/server.sh
     dest: /srv/server.sh

  - name: Updateing directory owner on /srv
    file:
     path: /srv
     owner: steam
     group: steam
     recurse: yes

  - name: Changeing permission on /srv/server.sh
    file:
     dest: /srv/server.sh
     mode: a+x
