---
- hosts: npf_gameservers-current-rack
  tasks:

  - name: Syncing /srv/csgo directory
    synchronize:
     src: /srv/csgo/
     dest: /srv/csgo
     delete: yes
     recursive: yes
     rsync_opts:
      - "--exclude=/srv/csgo/csgo/*.dem"
      - "--exclude=/srv/csgo/csgo/*.txt"
      - "--exclude=/srv/csgo/csgo/cfg/server.cfg"


  - name: Updatering general server.sh script
    synchronize:
     src: /srv/server.sh
     dest: /srv/server.sh
     checksum: yes

  - name: Check if servertype exists
    stat:
     path: /srv/gametype.config
    register: gametype_stats

  - name: Createing servertype
    shell: |
      printf 'csgo5v5' > /srv/gametype.config
    when: gametype_stats.stat.exists == False

  - name: Getting remote server type
    slurp:
     src: /srv/gametype.config
    register: gstype

  - name: Updatering config for CSGO 5v5
    synchronize:
     src: /srv/configs/5v5.cfg
     dest: /srv/csgo/csgo/cfg/server.cfg
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo5v5"'

  - name: Updatering commandline for CSGO 5v5
    synchronize:
     src: /srv/configs/5v5.commandline
     dest: /srv/csgo/commandline.setting
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo5v5"'

  - name: Updatering config for CSGO 5v5 Expo
    synchronize:
     src: /srv/configs/5v5-expo.cfg
     dest: /srv/csgo/csgo/cfg/server.cfg
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo5v5-expo"'

  - name: Updatering config for CSGO 2v2 Expo
    synchronize:
     src: /srv/configs/2v2-expo.cfg
     dest: /srv/csgo/csgo/cfg/server.cfg
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo2v2-expo"'

  - name: Updatering commandline for CSGO 2v2 Expo
    synchronize:
     src: /srv/configs/2v2-expo.commandline
     dest: /srv/csgo/commandline.setting
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo2v2-expo"'


  - name: Updateing config for CSGO 2v2
    synchronize:
     src: /srv/configs/2v2.cfg
     dest: /srv/csgo/csgo/cfg/server.cfg
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo2v2"'

  - name: Updateing server.sh for GOTV-Relay
    synchronize:
     src: /srv/configs/pro-relay.sh
     dest: /srv/server.sh
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo5v5-pro-relay"'

  - name: Updateing config for GOTV-Relay
    synchronize:
     src: /srv/configs/pro-relay.cfg
     dest: /srv/csgo/csgo/cfg/server.cfg
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo5v5-pro-relay"'

  - name: Updateing commandline for GOTV-Relay
    synchronize:
     src: /srv/configs/pro-relay.commandline
     dest: /srv/csgo/csgo/cfg/server.commandline
     checksum: yes
    when: 'gstype["content"] | b64decode == "csgo5v5-pro-relay"'

  - name: Updateing directory owner on /srv
    file:
     path: /srv
     owner: steam
     group: steam
     recurse: yes

  - name: Changeing permission on /srv/server.sh
    file:
     dest: /srv/server.sh
     mode: a+x

