---
- hosts: npf_gameservers_all
  gather_facts: no
  tasks:
  - name: copy filebeat.yml config files
    copy:
      src: assets/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root

  - name: reload daemons
    command: systemctl daemon-reload

  - name: make sure filebeat is started
    service: name=filebeat state=restarted enabled=yes

