---
- hosts: elasticsearch-data
  gather_facts: no
  tasks:
  - name: copy access config files
    copy:
      src: assets/access-aws.yml
      dest: /etc/elasticsearch/access.key
      owner: root
      group: elasticsearch

  - name: copy secret config files
    copy:
      src: assets/secret-aws.yml
      dest: /etc/elasticsearch/secret.key
      owner: root
      group: elasticsearch


  - name: create keystore
    command: /usr/share/elasticsearch/bin/elasticsearch-keystore create

  - name: add access to keystore
    command: cat /etc/elasticsearch/access.key | /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.default.access_key -xf

  - name: add secret to keystore
    command: cat /etc/elasticsearch/secret.key | /usr/share/elasticsearch/bin/elasticsearch-keystore add s3.client.default.secret_key -xf


  - name: make sure elasticsearch is started
    service: name=elasticsearch state=restarted enabled=yes

