---
- hosts: elasticsearch
  gather_facts: no
  tasks:
#  - name: install es s3 plugin
#    command: /usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 --batch
  - name: restart elasticsearch
    service: name=elasticsearch state=restarted
