---
- hosts: elasticsearch-master
  gather_facts: no
  tasks:
  - name: copy master.yml config files
    copy:
      src: assets/master.yml
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: elasticsearch

  - name: reload daemons
    command: systemctl daemon-reload

  - name: make sure elasticsearch is started
    service: name=elasticsearch state=restarted enabled=yes

