---
- hosts: elasticsearch
  gather_facts: yes
  tasks:
  - name: apt upgrade
    apt:
      name: curl
      state: present
  - name: install java
    apt:
      name: openjdk-8-jre-headless
      state: present

  - name: download es
    command: curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.3.1-amd64.deb
  
  - name: install es
    command: dpkg -i elasticsearch-7.3.1-amd64.deb

